# permissions for end users to edit helms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-editor-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - helms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - helms/status
  verbs:
  - get
