# permissions for end users to view helms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-viewer-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - helms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - helms/status
  verbs:
  - get
